### ISSUE TITLE
Debian 9 service support broken

### ISSUE THREAD

**Issue by nwmcsween** [itamae-kitchen/mruby-specinfra#6] opened 2018-01-22 23:04 UTC
The mruby-specinfra code expects `service` and `update-rc.d` to work for debian 9 but a large portion of debian software in 9 doesn't bundle systemd wrappers for /etc/init.d thus breaking service use with mruby-specinfra

**Comment by k0kubun** [comment] 2018-01-23 03:40
See also: https://github.com/k0kubun/mruby-specinfra/pull/5

**Comment by nwmcsween** [comment] 2018-01-23 03:49
I had to edit debian_release to 8 for mitamae to work otherwise it tries to
use service and update-rc.d which doesn't work due to /etc/init.d not
having the files.

**Comment by k0kubun** [comment] 2019-12-30 09:19
Hi. I updated mruby-specinfra's base to the latest specinfra v2.82.4. Please check if the problem is fixed in mitamae v1.10.0 using it.

If the issue persists, maybe the problem should be fixed in specinfra first, because mruby-specinfra is now almost mirroring specinfra's code.

**Closed by k0kubun** 2019-12-30 09:19 UTC
